patch:
  #"style/color_scheme": ink   # 选词皮肤
  #"style/font_point": 18      # 字体大小
  #style/horizontal: true      # 候選橫排
  #style/inline_preedit: true  # 內嵌編碼（僅支持TSF）

  # 關閉中文輸入
  # @see [http://code.google.com/p/rimeime/wiki/CustomizationGuide#在特定程序裏關閉中文輸入]
  #
  # Bundle Identifier 查找方法：
  # 右键『应用.app』-> 显示包内容
  # Contents/Info.plist -> BundleIdentifier
  #           Bundle Identifier
  app_options/com.apple.Xcode:
    ascii_mode: true
  app_options/org.vim.MacVim:
    ascii_mode: true
  app_options/com.google.Chrome:
    ascii_mode: true
  app_options/org.mozilla.firefox:
    ascii_mode: true
  app_options/com.apple.Safari:
    ascii_mode: true
  app_options/com.operasoftware.Opera:
    ascii_mode: true
  app_options/org.keepassx.keepassx:
    ascii_mode: true
  app_options/com.apple.Spotlight:
    ascii_mode: true
